baseurl = "/"
languageCode = "en-us"
title = "Neighborhood of Make Believe"

[params]
  description = ""

[[menu.main]]
    name = "About"
    url  = "/about"
    weight = 0
[[menu.main]]
    name = "Shows"
    url  = "/shows"
    weight = 1
[[menu.main]]
    name = "Music"
    url  = "/music"
    weight = 2
[[menu.main]]
    name = "Contact"
    url  = "/contact"
    weight = 3

